### ISSUE TITLE
ISSUE: chr10_MATERNAL:21,534,154-21,534,276

### ISSUE THREAD

**Issue by jzook** [marbl/HG002-issues#416]
Unusual 8bp error in C homopolymer in assembly

<img width="1500" alt="Screenshot 2023-03-08 at 8 32 42 PM" src="https://user-images.githubusercontent.com/2439798/223892268-096ffb07-8be7-4411-aac8-12584bd7cc56.png">

**Comment by nhansen** [comment]
Strangely, the curated correction sets led to a 10 base deletion correction applied to v0.7, but the resulting alignments on v0.9 look reasonable (see below). The long reads' consensus calls were very variable on this homopolymer run (as seen in Justin's screenshot above) which must have caused the assembler to botch it badly. 
<img width="1251" alt="image" src="https://github.com/marbl/HG002-issues/assets/2365395/e9383e99-0d13-402c-950f-6214f8cca550">
